### ISSUE TITLE
Error installing rohit43/DiabetesTxPath

### ISSUE THREAD

**Issue by cukarthik** [rohit43/DiabetesTxPath#1]
When I run: 
> install_github("rohit43/DiabetesTxPath")

I get the follow error:

> ERROR: dependencies ‘DatabaseConnector’, ‘FeatureExtraction’, ‘CohortMethod’, ‘OhdsiSharing’ are not available for package ‘DiabetesTxPath’
> * removing ‘/usr/local/lib/R/site-library/DiabetesTxPath’

**Comment by rohit43** [comment]
Please install DatabaseConnector, FeatureExtraction, CohortMethod and OhdsiSharing individually and then try installing DiabetesTxPath
