### ISSUE TITLE
Error running runCompleteStudy()

### ISSUE THREAD

**Issue by jepark315** [rohit43/DiabetesTxPath#5]
Hello,
While running runCompleteStudy(), I had this error below.
I think it's because of the table name it is using..
How can I fix this?
Any comment would be appreciated. Thank you.

`Error : Error executing SQL :
java.sql.SQLSyntaxErrorException : ORA-00955`

**Comment by rohit43** [comment]
Hi,
Never encountered this error before.
You can try the following:
1) Check if the database connection is setup properly.
2) check if the table already exists in your database, if yes, then please remove it and try it again.

Other than this, I am not sure what would be the reason. 

- Rohit

**Comment by jepark315** [comment]
> Hi, Never encountered this error before. You can try the following: 1) Check if the database connection is setup properly. 2) check if the table already exists in your database, if yes, then please remove it and try it again. Other than this, I am not sure what would be the reason. - Rohit
> […](#)
> On Nov 28, 2018, at 18:06, jepark315 ***@***.***> wrote: Error executing SQL : java.sql.SQLSyntaxErrorException : ORA-00955

I am not really familiar with SQL stuff so could you help me out with this one?
I think  I'm supposed to check if the table already exists in your database, if yes, then please remove it and try it again. but this database is the hospital's. so I'm not really accessible or able to remove the database.. so what could be other solutions?

This package is so useful and helpful for my study, so I really need it to work out.

Thank you very much.
