### ISSUE TITLE
error : java.lang.NoSuchMethodException 

### ISSUE THREAD

**Issue by jepark315** [rohit43/DiabetesTxPath#8]
Why is the error below coming up and how could I fix this?
![diabetestxpath_error](https://user-images.githubusercontent.com/43940996/49847664-9e186500-fe14-11e8-8838-4cc6792a2bdf.png)

**Comment by rohit43** [comment]
Try updating RJava

**Comment by rohit43** [comment]
Try with FeatureExtraction 2.1.5
