### ISSUE TITLE
Can't read README

### ISSUE THREAD

**Issue by schuemie** [rohit43/DiabetesTxPath#9]
Its some sort of Word document?

**Comment by rohit43** [comment]
Hi Martijn,
It’s a .RMD and was rendering properly into an html a while back. Don’t know why it would not render properly.

**Comment by schuemie** [comment]
Ah, you may want to start by deleting the html file. Then, I would turn the Rmd file into a md file (GitHub doesn't know what to do with a Rmd file). 

You can see any OHDSI GitHub repo for examples (e.g. [this one](https://github.com/OHDSI/OhdsiStudies/blob/master/README.md))

**Comment by rohit43** [comment]
Thanks. Done!

**Comment by schuemie** [comment]
Thanks!
